-- 이번 주 질문 답변 게시판 — Supabase 테이블 + RLS
-- Supabase 대시보드 → SQL Editor 에 붙여넣고 실행하세요.
-- (anon 키로 익명 읽기/쓰기만 허용. 개인정보·연락처는 받지 않습니다.)

create table if not exists public.mb_weekly_answers (
  id          bigint generated by default as identity primary key,
  question_id text        not null,
  nickname    text,
  answer      text        not null,
  created_at  timestamptz not null default now()
);

-- 같은 주 답변 조회를 빠르게
create index if not exists mb_weekly_answers_qid_idx
  on public.mb_weekly_answers (question_id, created_at desc);

alter table public.mb_weekly_answers enable row level security;

-- 익명 읽기 허용 (답변은 모두에게 공개)
drop policy if exists "mb_weekly_answers anon read" on public.mb_weekly_answers;
create policy "mb_weekly_answers anon read"
  on public.mb_weekly_answers
  for select to anon
  using (true);

-- 익명 쓰기 허용 (길이 제한으로 남용 방지)
drop policy if exists "mb_weekly_answers anon insert" on public.mb_weekly_answers;
create policy "mb_weekly_answers anon insert"
  on public.mb_weekly_answers
  for insert to anon
  with check (
    char_length(answer) between 1 and 300
    and (nickname is null or char_length(nickname) <= 20)
    and char_length(question_id) <= 40
  );
